### ISSUE TITLE
Why is there an "-s" parameter passed to the MOSFET_v5_ML.py script? It doesn't seem to be used but is present in the instructions. 

### ISSUE THREAD

**Issue by eduand-alvarez** [oneapi-src/digital-twin#1]
![image](https://user-images.githubusercontent.com/57263404/197572918-557c006f-7177-4dde-beba-8fd79a34e11b.png)

Not actually parsed or used in the script.

![image](https://user-images.githubusercontent.com/57263404/197572998-45d6e0a0-20ed-4cf3-8663-53d390083a9e.png)

It seems that the parameter alias is just wrong because the script uses "-n" for data length, but the instructions say to use "-s"

**Comment by raoberman** [comment]
Hi @eduand-alvarez thank you for your feedback, you are correct - the "-s" should be "-n" in the documentation.

This will be addressed in an upcoming update to the repo.

**Comment by raoberman** [comment]
Closing this issue, as it has been addressed in the latest update to the repository. This thread will no longer be monitored. If you experience a new issue or a continuation of this issue, please open a new thread. Thank you!
