### ISSUE TITLE
Training and Prediction times are missing units

### ISSUE THREAD

**Issue by tarekradi** [oneapi-src/digital-twin#4]
Are these seconds? Milliseconds? Please update the script to call this out clearly. 
Also, what is "Synthetic data shape 120000 10". What are those numbers? and what is that space between them? Please update the script to make this clear.

INFO:root:===== Running benchmarks for stock =====
INFO:root:===== Generating Synthetic Data =====
INFO:root:Synthetic data shape 120000 10
INFO:root:===== Running Benchmarks for XGB Regression =====
INFO:root:Training time = 5.732429027557373
INFO:root:Prediction time = 0.0826106071472168
INFO:root:Mean SQ Error: 0.021
INFO:root:

INFO:root:===== Running benchmarks for oneAPI tech =====
INFO:root:===== Generating Synthetic Data =====
INFO:root:Synthetic data shape 120000 10
INFO:root:===== Running Benchmarks for XGB Regression =====
INFO:root:Training time = 6.233368158340454
INFO:root:Prediction time = 0.0852348804473877
INFO:root:daal4py Prediction time = 0.08125638961791992
INFO:root:Mean SQ Error: 0.024
INFO:root:daal4py Mean SQ Error: 0.024
INFO:root:

INFO:root:===== Running benchmarks for stock =====
INFO:root:===== Generating Synthetic Data =====
INFO:root:Synthetic data shape 120000 10
INFO:root:===== Running Benchmarks for XGB Regression =====
INFO:root:Training time = 6.020364046096802
INFO:root:Prediction time = 0.09345483779907227
INFO:root:Mean SQ Error: 0.023
INFO:root:

INFO:root:===== Running benchmarks for oneAPI tech =====
INFO:root:===== Generating Synthetic Data =====
INFO:root:Synthetic data shape 120000 10
INFO:root:===== Running Benchmarks for XGB Regression =====
INFO:root:Training time = 6.112257957458496
INFO:root:Prediction time = 0.09519767761230469
INFO:root:daal4py Prediction time = 0.07418465614318848
INFO:root:Mean SQ Error: 0.022
INFO:root:daal4py Mean SQ Error: 0.022

**Comment by raoberman** [comment]
Hi @tarekradi 

The time numbers in the output are measured in seconds, and the `Synthetic data shape 120000 10` refers to the number of rows and columns, respectively, for the dataset used. The space between each section is used to denote separate runs that have been saved to the same log file.

Ex (for saving to the same log file `XGB_stock.log`):

#first time you ran the script
INFO:root:===== Running benchmarks for stock =====
INFO:root:===== Generating Synthetic Data =====
INFO:root:Synthetic data shape 120000 10
INFO:root:===== Running Benchmarks for XGB Regression =====
INFO:root:Training time = 5.732429027557373
INFO:root:Prediction time = 0.0826106071472168
INFO:root:Mean SQ Error: 0.021
INFO:root:

#second time you ran the script to the same log file
INFO:root:===== Running benchmarks for oneAPI tech =====
INFO:root:===== Generating Synthetic Data =====
INFO:root:Synthetic data shape 120000 10
INFO:root:===== Running Benchmarks for XGB Regression =====
INFO:root:Training time = 6.233368158340454
INFO:root:Prediction time = 0.0852348804473877
INFO:root:daal4py Prediction time = 0.08125638961791992
INFO:root:Mean SQ Error: 0.024
INFO:root:daal4py Mean SQ Error: 0.024
INFO:root:


I have sent you an email on this with more information.

**Comment by tarekradi** [comment]
Thank you, Rachel. How do i submit a request for the source code to change as follows?


        logger.info("Training time = %s", train_time, " seconds.")
        logger.info("Prediction time = %s", pred_time, " seconds.")

and
    logger.info("Synthetic data shape %s", ' '.join(map(str, list(synth_data.shape)))," rows and columns respectively.")

**Comment by raoberman** [comment]
@tarekradi  As discussed offline, please submit a pull request with these changes and it will be reviewed for approval.
